const PlacesPage = () => {
  return (
    <main>
      <h1 className="mb-10 text-3xl font-bold">Мережа навчального закладу</h1>
      <table>
        <thead>
          <tr>
            <th>Клас</th>
            <th>Кількість учнів в класі</th>
            <th>Вільні місця</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1-А</td>
            <td>20</td>
            <td>10</td>
          </tr>
          <tr>
            <td>1-Б</td>
            <td>20</td>
            <td>10</td>
          </tr>
          <tr>
            <td>2-А</td>
            <td>22</td>
            <td>8</td>
          </tr>
          <tr>
            <td>2-Б</td>
            <td>25</td>
            <td>5</td>
          </tr>
          <tr>
            <td>3-А</td>
            <td>26</td>
            <td>4</td>
          </tr>
          <tr>
            <td>3-Б</td>
            <td>27</td>
            <td>3</td>
          </tr>
          <tr>
            <td>4-А</td>
            <td>23</td>
            <td>7</td>
          </tr>
          <tr>
            <td>4-Б</td>
            <td>23</td>
            <td>7</td>
          </tr>
          <tr>
            <td>4-В</td>
            <td>25</td>
            <td>5</td>
          </tr>
          <tr>
            <td>5-А</td>
            <td>31</td>
            <td>-</td>
          </tr>
          <tr>
            <td>5-Б</td>
            <td>29</td>
            <td>1</td>
          </tr>
          <tr>
            <td>6-А</td>
            <td>25</td>
            <td>5</td>
          </tr>
          <tr>
            <td>6-Б</td>
            <td>34</td>
            <td>-</td>
          </tr>
          <tr>
            <td>6-В</td>
            <td>26</td>
            <td>4</td>
          </tr>
          <tr>
            <td>7-А</td>
            <td>24</td>
            <td>6</td>
          </tr>
          <tr>
            <td>7-Б</td>
            <td>24</td>
            <td>6</td>
          </tr>
          <tr>
            <td>8-А</td>
            <td>25</td>
            <td>5</td>
          </tr>
          <tr>
            <td>8-Б</td>
            <td>29</td>
            <td>1</td>
          </tr>
          <tr>
            <td>9-А</td>
            <td>31</td>
            <td>-</td>
          </tr>
          <tr>
            <td>9-Б</td>
            <td>32</td>
            <td>-</td>
          </tr>
        </tbody>
      </table>
    </main>
  );
};

export default PlacesPage;
